site_name: Composable Form Specification
copyright: © 2017 <a href="http://dairystatedesigns.com" target="_blank">Dairy State Designs</a>
theme:
  name: null
  custom_dir: cinder
repo_url: https://github.com/DairyStateDesigns/composable-forms
google_analytics: ['UA-35264404-5', 'forms.dairystatedesigns.com']
markdown_extensions:
  - toc:
      permalink: True
extra_css:
  - styles.css
pages:
  - Home: index.md
  - User Docs:
    - Overview: user.md
    - 'Form Component Reference': user/form.md
    - 'Input Component Reference': user/input.md
    - 'Field Component Reference': user/field.md
    - 'FormList Component Reference': user/list.md
    - 'ErrorsBlock Component Reference': user/errors.md
    - 'Validator Reference': user/validation.md
  - Spec:
    - Overview: spec.md
    - 'Form Component Specification': spec/form.md
    - 'Input Component Specification': spec/input.md
    - 'Field Component Specification': spec/field.md
    - 'FormList Component Specification': spec/list.md
    - 'ErrorsBlock Component Specification': spec/errors.md
    - 'Validator Specification': spec/validation.md
  - ReactoForm: reacto-form.md
  - Packages: packages.md
